// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// print_list2
void print_list2(List x);
RcppExport SEXP _ELRSepTests_print_list2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    print_list2(x);
    return R_NilValue;
END_RCPP
}
// outer_optimize_rcpp
List outer_optimize_rcpp(const arma::mat& scrsAug, const arma::vec& betaInit, const arma::vec& gammaInit, double aInit, int LTest, int JTest, int numParsS, const IntegerVector& SepInd, int mOtr, int LSmax, int mInr, double tolInr, double tolOtr, bool verb);
RcppExport SEXP _ELRSepTests_outer_optimize_rcpp(SEXP scrsAugSEXP, SEXP betaInitSEXP, SEXP gammaInitSEXP, SEXP aInitSEXP, SEXP LTestSEXP, SEXP JTestSEXP, SEXP numParsSSEXP, SEXP SepIndSEXP, SEXP mOtrSEXP, SEXP LSmaxSEXP, SEXP mInrSEXP, SEXP tolInrSEXP, SEXP tolOtrSEXP, SEXP verbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type scrsAug(scrsAugSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type betaInit(betaInitSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gammaInit(gammaInitSEXP);
    Rcpp::traits::input_parameter< double >::type aInit(aInitSEXP);
    Rcpp::traits::input_parameter< int >::type LTest(LTestSEXP);
    Rcpp::traits::input_parameter< int >::type JTest(JTestSEXP);
    Rcpp::traits::input_parameter< int >::type numParsS(numParsSSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type SepInd(SepIndSEXP);
    Rcpp::traits::input_parameter< int >::type mOtr(mOtrSEXP);
    Rcpp::traits::input_parameter< int >::type LSmax(LSmaxSEXP);
    Rcpp::traits::input_parameter< int >::type mInr(mInrSEXP);
    Rcpp::traits::input_parameter< double >::type tolInr(tolInrSEXP);
    Rcpp::traits::input_parameter< double >::type tolOtr(tolOtrSEXP);
    Rcpp::traits::input_parameter< bool >::type verb(verbSEXP);
    rcpp_result_gen = Rcpp::wrap(outer_optimize_rcpp(scrsAug, betaInit, gammaInit, aInit, LTest, JTest, numParsS, SepInd, mOtr, LSmax, mInr, tolInr, tolOtr, verb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ELRSepTests_print_list2", (DL_FUNC) &_ELRSepTests_print_list2, 1},
    {"_ELRSepTests_outer_optimize_rcpp", (DL_FUNC) &_ELRSepTests_outer_optimize_rcpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_ELRSepTests(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
