# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

print_list2 <- function(x) {
    invisible(.Call(`_ELRSepTests_print_list2`, x))
}

outer_optimize_rcpp <- function(scrsAug, betaInit, gammaInit, aInit, LTest, JTest, numParsS, SepInd, mOtr, LSmax, mInr, tolInr, tolOtr, verb = FALSE) {
    .Call(`_ELRSepTests_outer_optimize_rcpp`, scrsAug, betaInit, gammaInit, aInit, LTest, JTest, numParsS, SepInd, mOtr, LSmax, mInr, tolInr, tolOtr, verb)
}

